site_name: RENware Software Systems
site_author: 'Petre Iordanescu, RENware Software Systems'
copyright: 'Copyright (c) RENware Software Systems'


nav:
    - Home: 'index.md'
    - Services: 'services.md'
    - Solutions:
        - Solutions: 'solutions.md'
        - ALPHA REN Integrator: 'http://arint.renware.eu'
        - COSANA: 'http://cosana.renware.eu'
        - PM Office: 'http://pmo.renware.eu'
        - USALAS: 'http://uslas.renware.eu'
    - Resources:
        - Resources: 'resources.md'
        - SDEVEN methodology: 'http://sdeven.renware.eu'
        - Buy from RENware: 'buy_from_renware.md'
        - Learning @ RENware: 'http://learning.renware.eu'
    - About: 'about.md'
    - Contact: 'contact.md'
    #- old_index: 'old_index.html' #FIXME drop me when finish









markdown_extensions:
    - admonition
    - tables
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences: #NOTE: [petre iordanescu]: is very important to respect syntax ref `-` character at beginning of items (otherwise not right JSON result !)
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true


#NOTE required to render `mermaid` diagrams
extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js



plugins:
    - search
    - include-markdown
    #NOTE `print-site` is not needed in `ren portal` project
    # - print-site: #NOTE: put print-site to the bottom of the plugins that may might alter your site navigation (affect order of sections in generated HTML)
    #    add_to_navigation: true
    #    print_page_title: 'Full SDEVEN Manual'
    #    add_full_urls: true
    #    add_table_of_contents: true
    #NOTE `pdf-with-js` extension is not needed in RENware portal !!!
    # - pdf-with-js:
    #     enable: true



#NOTE provide material theme
theme:
    logo: pictures/REN_stamp_logo_transparent.png
    name: material
    features:
        - navigation.tabs #NOTE level 2 on left navigation side bar, level 1 on top navigation bar
        - navigation.tracking
        - navigation.tabs.sticky
        - navigation.path
        - toc.integrate #NOTE integrate TOC in left navbar
    palette:
        primary: light blue # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/ for other color options
    icon:
        admonition:
            note: fontawesome/solid/note-sticky
            abstract: fontawesome/solid/book
            info: fontawesome/solid/circle-info
            tip: fontawesome/solid/bullhorn
            success: fontawesome/solid/check
            question: fontawesome/solid/circle-question
            warning: fontawesome/solid/triangle-exclamation
            failure: fontawesome/solid/bomb
            danger: fontawesome/solid/skull
            bug: fontawesome/solid/robot
            example: fontawesome/solid/flask
            quote: fontawesome/solid/quote-left




#NOTE directory where start to search or markdown sources
docs_dir: './doc_src'


#NOTE root directory where to be generated portal (should be `./static_portal`)
site_dir: './static_portal'



#NOTE other useful configurations
use_directory_urls: false #NOTE allow link between pages to work properly when used as OFFLINE deployment (ie, static site an "callable" as `file:///...`)


